### ISSUE TITLE
Why does this require exactly tensorflow 1.13.1?

### ISSUE THREAD

**Issue by DanielPBak** [diplomacy/research#1]
Congrats on your work!

I'm trying to install this library via pip (since I would like to use the gym environment); is there a reason that tensorflow 1.13.1 is required?

**Comment by ppaquette** [comment]
Some of the layers are heavily dependent on the internal TF components.

You can have a look here:

https://github.com/diplomacy/research/blob/master/diplomacy_research/utils/tensorflow.py#L26

I have pinned the version to make sure the code doesn't break with the v2.0 changes. There were typically a handful of changes required between versions, but nothing substantial.

If you link to another TF version, make sure you run the unit tests with ./run_tests.sh to detect any potential issues.

**Comment by DanielPBak** [comment]
Would it be too difficult to make only the environment (which I am guessing does not rely on TF internals) available on pypi?

I'm guessing it is but I figured I'd try asking!

**Comment by ppaquette** [comment]
The environment is available at: https://github.com/diplomacy/diplomacy and can be installed with `pip install diplomacy`. It does not have any dependencies on Tensorflow.

If you mean the gym env, it's basically just a very thinny wrapper (100 lines of code) around the diplomacy env. You most likely don't really need it.

step -> game.set_orders(power_name, orders)
reset -> Game()
process -> game.process()

So you could run simulations with:

```
import random
from diplomacy import Game

def get_orders(game, power_name):
    """ Returns random orders for the power """
    possible_orders = game.get_all_possible_orders()
    orderable_locs = game.get_orderable_locations(power_name)
    return [random.choice(possible_orders[loc]) for loc in orderable_locs if possible_orders[loc]]

game = Game()                                                           # equivalent of reset()
while not game.is_game_done:
    # you can get the state directly from the game object, or from game.get_state()
    for power_name in game.powers:
        game.set_orders(power_name, get_orders(game, power_name))       # equivalent of step()
    game.process()
```

This repo contains the model, which obviously requires TF.

**Comment by DanielPBak** [comment]
Thank you very much!
