### ISSUE TITLE
Dataset access?

### ISSUE THREAD

**Issue by malkin1729** [diplomacy/research#8]
Hello,

Could you please share the dataset used to train the models, or let me know how I can obtain it?
(I have written to the address in the readme and gotten no response.)

Thank you.

**Comment by ppaquette** [comment]
Can you send a follow-up email to the email in the README (webdipmod (at) gmail.com) and add me in cc (pcpaquette (at) gmail.com). We are all quite busy, so it might have fell between the cracks.

**Comment by malkin1729** [comment]
I will do this. Thank you for your help.
